import { Box, Button } from '@kuma-ui/core'
import Head from "next/head";
import { useEffect, useState } from 'react'

export default function Home() {

  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDark])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Box as="h1" color="colors.primary">
          This is your homepage
        </Box>
        <Button onClick={() => setIsDark(v => !v)}>Toggle theme</Button>
      </Box>
    </>
  );
}
